// Code generated by ogen, DO NOT EDIT.

package client

// DeleteSourceParams is parameters of deleteSource operation.
type DeleteSourceParams struct {
	SourceID int64
}

// GetSourceParams is parameters of getSource operation.
type GetSourceParams struct {
	SourceID int64
}

// UpdateSourceParams is parameters of updateSource operation.
type UpdateSourceParams struct {
	SourceID int64
}
