// Code generated by ogen, DO NOT EDIT.

package client

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// WorkspaceApiKey provides workspaceApiKey security value.
	WorkspaceApiKey(ctx context.Context, operationName OperationName, client *Client) (WorkspaceApiKey, error)
}

func (s *Client) securityWorkspaceApiKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.WorkspaceApiKey(ctx, operationName, s)
	if err != nil {
		return errors.Wrap(err, "security source \"WorkspaceApiKey\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
