// Code generated by ogen, DO NOT EDIT.

package censusmanagement

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateDatasetOperation     OperationName = "CreateDataset"
	CreateDestinationOperation OperationName = "CreateDestination"
	CreateSourceOperation      OperationName = "CreateSource"
	CreateSyncOperation        OperationName = "CreateSync"
	DeleteDatasetOperation     OperationName = "DeleteDataset"
	DeleteDestinationOperation OperationName = "DeleteDestination"
	DeleteSourceOperation      OperationName = "DeleteSource"
	DeleteSyncOperation        OperationName = "DeleteSync"
	GetApiV1Operation          OperationName = "GetApiV1"
	GetDatasetOperation        OperationName = "GetDataset"
	GetDestinationOperation    OperationName = "GetDestination"
	GetSourceOperation         OperationName = "GetSource"
	GetSyncOperation           OperationName = "GetSync"
	UpdateDatasetOperation     OperationName = "UpdateDataset"
	UpdateDestinationOperation OperationName = "UpdateDestination"
	UpdateSourceOperation      OperationName = "UpdateSource"
	UpdateSyncOperation        OperationName = "UpdateSync"
)
