// Code generated by ogen, DO NOT EDIT.

package censusmanagement

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteSourceParams is parameters of deleteSource operation.
type DeleteSourceParams struct {
	SourceID int64
}

func unpackDeleteSourceParams(packed middleware.Parameters) (params DeleteSourceParams) {
	{
		key := middleware.ParameterKey{
			Name: "source_id",
			In:   "path",
		}
		params.SourceID = packed[key].(int64)
	}
	return params
}

func decodeDeleteSourceParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteSourceParams, _ error) {
	// Decode path: source_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "source_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.SourceID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "source_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetSourceParams is parameters of getSource operation.
type GetSourceParams struct {
	SourceID int64
}

func unpackGetSourceParams(packed middleware.Parameters) (params GetSourceParams) {
	{
		key := middleware.ParameterKey{
			Name: "source_id",
			In:   "path",
		}
		params.SourceID = packed[key].(int64)
	}
	return params
}

func decodeGetSourceParams(args [1]string, argsEscaped bool, r *http.Request) (params GetSourceParams, _ error) {
	// Decode path: source_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "source_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.SourceID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "source_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateSourceParams is parameters of updateSource operation.
type UpdateSourceParams struct {
	SourceID int64
}

func unpackUpdateSourceParams(packed middleware.Parameters) (params UpdateSourceParams) {
	{
		key := middleware.ParameterKey{
			Name: "source_id",
			In:   "path",
		}
		params.SourceID = packed[key].(int64)
	}
	return params
}

func decodeUpdateSourceParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateSourceParams, _ error) {
	// Decode path: source_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "source_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.SourceID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "source_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
