// Code generated by ogen, DO NOT EDIT.

package censusmanagement

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleWorkspaceApiKey handles workspaceApiKey security.
	HandleWorkspaceApiKey(ctx context.Context, operationName OperationName, t WorkspaceApiKey) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesWorkspaceApiKey = map[string][]string{
	CreateDatasetOperation:         []string{},
	CreateDestinationOperation:     []string{},
	CreateSourceOperation:          []string{},
	DeleteDatasetOperation:         []string{},
	DeleteDestinationOperation:     []string{},
	DeleteSourceOperation:          []string{},
	GetApiV1Operation:              []string{},
	GetDatasetOperation:            []string{},
	GetDestinationOperation:        []string{},
	GetSourceOperation:             []string{},
	RefreshDatasetColumnsOperation: []string{},
	UpdateDatasetOperation:         []string{},
	UpdateDestinationOperation:     []string{},
	UpdateSourceOperation:          []string{},
}

func (s *Server) securityWorkspaceApiKey(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t WorkspaceApiKey
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesWorkspaceApiKey[operationName]
	rctx, err := s.sec.HandleWorkspaceApiKey(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// WorkspaceApiKey provides workspaceApiKey security value.
	WorkspaceApiKey(ctx context.Context, operationName OperationName, client *Client) (WorkspaceApiKey, error)
}

func (s *Client) securityWorkspaceApiKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.WorkspaceApiKey(ctx, operationName, s)
	if err != nil {
		return errors.Wrap(err, "security source \"WorkspaceApiKey\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
