// Code generated by ogen, DO NOT EDIT.

package censusmanagement

import (
	"io"
	"mime"
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"

	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/validate"
)

func decodeCreateSourceResponse(resp *http.Response) (res *IdResponseStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *IdResponseStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response IdResponse
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &IdResponseStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *StatusResponseStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response StatusResponse
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &StatusResponseStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeCreateSourceModelResponse(resp *http.Response) (res *IdResponseStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *IdResponseStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response IdResponse
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &IdResponseStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *StatusResponseStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response StatusResponse
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &StatusResponseStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeDeleteSourceResponse(resp *http.Response) (res *StatusResponseStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *StatusResponseStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response StatusResponse
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &StatusResponseStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *StatusResponseStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response StatusResponse
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &StatusResponseStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeDeleteSourceModelResponse(resp *http.Response) (res *StatusResponseStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *StatusResponseStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response StatusResponse
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &StatusResponseStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *StatusResponseStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response StatusResponse
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &StatusResponseStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeGetApiV1Response(resp *http.Response) (res GetApiV1Res, _ error) {
	// Convenient error response.
	defRes, err := func() (res *StatusResponseStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response StatusResponse
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &StatusResponseStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeGetSourceResponse(resp *http.Response) (res *SourceResponseStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *SourceResponseStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response SourceResponse
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &SourceResponseStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *StatusResponseStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response StatusResponse
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &StatusResponseStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeGetSourceModelResponse(resp *http.Response) (res *SourceModelResponseStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *SourceModelResponseStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response SourceModelResponse
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &SourceModelResponseStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *StatusResponseStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response StatusResponse
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &StatusResponseStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeUpdateSourceResponse(resp *http.Response) (res *SourceResponseStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *SourceResponseStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response SourceResponse
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &SourceResponseStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *StatusResponseStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response StatusResponse
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &StatusResponseStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeUpdateSourceModelResponse(resp *http.Response) (res *SourceModelResponseStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *SourceModelResponseStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response SourceModelResponse
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &SourceModelResponseStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *StatusResponseStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response StatusResponse
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &StatusResponseStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}
