// Code generated by ogen, DO NOT EDIT.

package censusmanagement

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteDatasetParams is parameters of deleteDataset operation.
type DeleteDatasetParams struct {
	DatasetID string
}

func unpackDeleteDatasetParams(packed middleware.Parameters) (params DeleteDatasetParams) {
	{
		key := middleware.ParameterKey{
			Name: "dataset_id",
			In:   "path",
		}
		params.DatasetID = packed[key].(string)
	}
	return params
}

func decodeDeleteDatasetParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteDatasetParams, _ error) {
	// Decode path: dataset_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "dataset_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.DatasetID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "dataset_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteDestinationParams is parameters of deleteDestination operation.
type DeleteDestinationParams struct {
	DestinationID string
}

func unpackDeleteDestinationParams(packed middleware.Parameters) (params DeleteDestinationParams) {
	{
		key := middleware.ParameterKey{
			Name: "destination_id",
			In:   "path",
		}
		params.DestinationID = packed[key].(string)
	}
	return params
}

func decodeDeleteDestinationParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteDestinationParams, _ error) {
	// Decode path: destination_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "destination_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.DestinationID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "destination_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteSourceParams is parameters of deleteSource operation.
type DeleteSourceParams struct {
	SourceID string
}

func unpackDeleteSourceParams(packed middleware.Parameters) (params DeleteSourceParams) {
	{
		key := middleware.ParameterKey{
			Name: "source_id",
			In:   "path",
		}
		params.SourceID = packed[key].(string)
	}
	return params
}

func decodeDeleteSourceParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteSourceParams, _ error) {
	// Decode path: source_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "source_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SourceID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "source_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteSyncParams is parameters of deleteSync operation.
type DeleteSyncParams struct {
	SyncID string
}

func unpackDeleteSyncParams(packed middleware.Parameters) (params DeleteSyncParams) {
	{
		key := middleware.ParameterKey{
			Name: "sync_id",
			In:   "path",
		}
		params.SyncID = packed[key].(string)
	}
	return params
}

func decodeDeleteSyncParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteSyncParams, _ error) {
	// Decode path: sync_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sync_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SyncID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sync_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetDatasetParams is parameters of getDataset operation.
type GetDatasetParams struct {
	DatasetID string
}

func unpackGetDatasetParams(packed middleware.Parameters) (params GetDatasetParams) {
	{
		key := middleware.ParameterKey{
			Name: "dataset_id",
			In:   "path",
		}
		params.DatasetID = packed[key].(string)
	}
	return params
}

func decodeGetDatasetParams(args [1]string, argsEscaped bool, r *http.Request) (params GetDatasetParams, _ error) {
	// Decode path: dataset_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "dataset_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.DatasetID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "dataset_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetDestinationParams is parameters of getDestination operation.
type GetDestinationParams struct {
	DestinationID string
}

func unpackGetDestinationParams(packed middleware.Parameters) (params GetDestinationParams) {
	{
		key := middleware.ParameterKey{
			Name: "destination_id",
			In:   "path",
		}
		params.DestinationID = packed[key].(string)
	}
	return params
}

func decodeGetDestinationParams(args [1]string, argsEscaped bool, r *http.Request) (params GetDestinationParams, _ error) {
	// Decode path: destination_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "destination_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.DestinationID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "destination_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetSourceParams is parameters of getSource operation.
type GetSourceParams struct {
	SourceID string
}

func unpackGetSourceParams(packed middleware.Parameters) (params GetSourceParams) {
	{
		key := middleware.ParameterKey{
			Name: "source_id",
			In:   "path",
		}
		params.SourceID = packed[key].(string)
	}
	return params
}

func decodeGetSourceParams(args [1]string, argsEscaped bool, r *http.Request) (params GetSourceParams, _ error) {
	// Decode path: source_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "source_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SourceID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "source_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetSyncParams is parameters of getSync operation.
type GetSyncParams struct {
	SyncID string
}

func unpackGetSyncParams(packed middleware.Parameters) (params GetSyncParams) {
	{
		key := middleware.ParameterKey{
			Name: "sync_id",
			In:   "path",
		}
		params.SyncID = packed[key].(string)
	}
	return params
}

func decodeGetSyncParams(args [1]string, argsEscaped bool, r *http.Request) (params GetSyncParams, _ error) {
	// Decode path: sync_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sync_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SyncID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sync_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateDatasetParams is parameters of updateDataset operation.
type UpdateDatasetParams struct {
	DatasetID string
}

func unpackUpdateDatasetParams(packed middleware.Parameters) (params UpdateDatasetParams) {
	{
		key := middleware.ParameterKey{
			Name: "dataset_id",
			In:   "path",
		}
		params.DatasetID = packed[key].(string)
	}
	return params
}

func decodeUpdateDatasetParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateDatasetParams, _ error) {
	// Decode path: dataset_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "dataset_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.DatasetID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "dataset_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateDestinationParams is parameters of updateDestination operation.
type UpdateDestinationParams struct {
	DestinationID string
}

func unpackUpdateDestinationParams(packed middleware.Parameters) (params UpdateDestinationParams) {
	{
		key := middleware.ParameterKey{
			Name: "destination_id",
			In:   "path",
		}
		params.DestinationID = packed[key].(string)
	}
	return params
}

func decodeUpdateDestinationParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateDestinationParams, _ error) {
	// Decode path: destination_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "destination_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.DestinationID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "destination_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateSourceParams is parameters of updateSource operation.
type UpdateSourceParams struct {
	SourceID string
}

func unpackUpdateSourceParams(packed middleware.Parameters) (params UpdateSourceParams) {
	{
		key := middleware.ParameterKey{
			Name: "source_id",
			In:   "path",
		}
		params.SourceID = packed[key].(string)
	}
	return params
}

func decodeUpdateSourceParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateSourceParams, _ error) {
	// Decode path: source_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "source_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SourceID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "source_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateSyncParams is parameters of updateSync operation.
type UpdateSyncParams struct {
	SyncID string
}

func unpackUpdateSyncParams(packed middleware.Parameters) (params UpdateSyncParams) {
	{
		key := middleware.ParameterKey{
			Name: "sync_id",
			In:   "path",
		}
		params.SyncID = packed[key].(string)
	}
	return params
}

func decodeUpdateSyncParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateSyncParams, _ error) {
	// Decode path: sync_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sync_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SyncID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sync_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
