// Code generated by ogen, DO NOT EDIT.

package client

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateSourceOperation OperationName = "CreateSource"
	DeleteSourceOperation OperationName = "DeleteSource"
	GetSourceOperation    OperationName = "GetSource"
	UpdateSourceOperation OperationName = "UpdateSource"
)
