// Code generated by ogen, DO NOT EDIT.

package censusmanagement

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateSourceOperation      OperationName = "CreateSource"
	CreateSourceModelOperation OperationName = "CreateSourceModel"
	DeleteSourceOperation      OperationName = "DeleteSource"
	DeleteSourceModelOperation OperationName = "DeleteSourceModel"
	GetApiV1Operation          OperationName = "GetApiV1"
	GetSourceOperation         OperationName = "GetSource"
	GetSourceModelOperation    OperationName = "GetSourceModel"
	UpdateSourceOperation      OperationName = "UpdateSource"
	UpdateSourceModelOperation OperationName = "UpdateSourceModel"
)
