// Code generated by ogen, DO NOT EDIT.

package censusmanagement

import (
	"fmt"

	"github.com/go-faster/errors"
)

func (s *StatusResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/ResponseStatus
type ResponseStatus string

const (
	ResponseStatusSuccess  ResponseStatus = "success"
	ResponseStatusUpdated  ResponseStatus = "updated"
	ResponseStatusCreated  ResponseStatus = "created"
	ResponseStatusDeleted  ResponseStatus = "deleted"
	ResponseStatusNotFound ResponseStatus = "not_found"
	ResponseStatusError    ResponseStatus = "error"
)

// AllValues returns all ResponseStatus values.
func (ResponseStatus) AllValues() []ResponseStatus {
	return []ResponseStatus{
		ResponseStatusSuccess,
		ResponseStatusUpdated,
		ResponseStatusCreated,
		ResponseStatusDeleted,
		ResponseStatusNotFound,
		ResponseStatusError,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ResponseStatus) MarshalText() ([]byte, error) {
	switch s {
	case ResponseStatusSuccess:
		return []byte(s), nil
	case ResponseStatusUpdated:
		return []byte(s), nil
	case ResponseStatusCreated:
		return []byte(s), nil
	case ResponseStatusDeleted:
		return []byte(s), nil
	case ResponseStatusNotFound:
		return []byte(s), nil
	case ResponseStatusError:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ResponseStatus) UnmarshalText(data []byte) error {
	switch ResponseStatus(data) {
	case ResponseStatusSuccess:
		*s = ResponseStatusSuccess
		return nil
	case ResponseStatusUpdated:
		*s = ResponseStatusUpdated
		return nil
	case ResponseStatusCreated:
		*s = ResponseStatusCreated
		return nil
	case ResponseStatusDeleted:
		*s = ResponseStatusDeleted
		return nil
	case ResponseStatusNotFound:
		*s = ResponseStatusNotFound
		return nil
	case ResponseStatusError:
		*s = ResponseStatusError
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type StatusResponse struct {
	Status  StatusResponseStatus `json:"status"`
	Message OptString            `json:"message"`
}

// GetStatus returns the value of Status.
func (s *StatusResponse) GetStatus() StatusResponseStatus {
	return s.Status
}

// GetMessage returns the value of Message.
func (s *StatusResponse) GetMessage() OptString {
	return s.Message
}

// SetStatus sets the value of Status.
func (s *StatusResponse) SetStatus(val StatusResponseStatus) {
	s.Status = val
}

// SetMessage sets the value of Message.
func (s *StatusResponse) SetMessage(val OptString) {
	s.Message = val
}

// StatusResponseStatus represents sum type.
type StatusResponseStatus struct {
	Type           StatusResponseStatusType // switch on this field
	ResponseStatus ResponseStatus
	Int            int
}

// StatusResponseStatusType is oneOf type of StatusResponseStatus.
type StatusResponseStatusType string

// Possible values for StatusResponseStatusType.
const (
	ResponseStatusStatusResponseStatus StatusResponseStatusType = "ResponseStatus"
	IntStatusResponseStatus            StatusResponseStatusType = "int"
)

// IsResponseStatus reports whether StatusResponseStatus is ResponseStatus.
func (s StatusResponseStatus) IsResponseStatus() bool {
	return s.Type == ResponseStatusStatusResponseStatus
}

// IsInt reports whether StatusResponseStatus is int.
func (s StatusResponseStatus) IsInt() bool { return s.Type == IntStatusResponseStatus }

// SetResponseStatus sets StatusResponseStatus to ResponseStatus.
func (s *StatusResponseStatus) SetResponseStatus(v ResponseStatus) {
	s.Type = ResponseStatusStatusResponseStatus
	s.ResponseStatus = v
}

// GetResponseStatus returns ResponseStatus and true boolean if StatusResponseStatus is ResponseStatus.
func (s StatusResponseStatus) GetResponseStatus() (v ResponseStatus, ok bool) {
	if !s.IsResponseStatus() {
		return v, false
	}
	return s.ResponseStatus, true
}

// NewResponseStatusStatusResponseStatus returns new StatusResponseStatus from ResponseStatus.
func NewResponseStatusStatusResponseStatus(v ResponseStatus) StatusResponseStatus {
	var s StatusResponseStatus
	s.SetResponseStatus(v)
	return s
}

// SetInt sets StatusResponseStatus to int.
func (s *StatusResponseStatus) SetInt(v int) {
	s.Type = IntStatusResponseStatus
	s.Int = v
}

// GetInt returns int and true boolean if StatusResponseStatus is int.
func (s StatusResponseStatus) GetInt() (v int, ok bool) {
	if !s.IsInt() {
		return v, false
	}
	return s.Int, true
}

// NewIntStatusResponseStatus returns new StatusResponseStatus from int.
func NewIntStatusResponseStatus(v int) StatusResponseStatus {
	var s StatusResponseStatus
	s.SetInt(v)
	return s
}

// StatusResponseStatusCode wraps StatusResponse with StatusCode.
type StatusResponseStatusCode struct {
	StatusCode int
	Response   StatusResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *StatusResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *StatusResponseStatusCode) GetResponse() StatusResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *StatusResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *StatusResponseStatusCode) SetResponse(val StatusResponse) {
	s.Response = val
}

type WorkspaceApiKey struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *WorkspaceApiKey) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *WorkspaceApiKey) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *WorkspaceApiKey) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *WorkspaceApiKey) SetRoles(val []string) {
	s.Roles = val
}
