openapi: 3.0.3
info:
  title: Census Sync API
  version: "1.0"
paths:
  /api/v1/syncs:
    post:
      summary: Create a new sync
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrUpdateSyncBody'
      responses:
        '201':
          description: Sync created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSyncResponse'

  /api/v1/syncs/{sync_id}:
    patch:
      summary: Update a sync
      parameters:
        - name: sync_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the sync to update.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrUpdateSyncBody'
      responses:
        '200':
          description: Sync updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSyncResponse'

    get:
      summary: Fetch a sync
      parameters:
        - name: sync_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the sync to retrieve.
      responses:
        '200':
          description: Sync details retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchSyncResponse'

components:
  schemas:

    CreateOrUpdateSyncBody:
      type: object
      properties:
        label:
          type: string
          description: A label to give to this sync.
        operation:
          type: string
          description: How records are synced to the destination.
          enum:
            - append
            - insert
            - mirror
            - update
            - upsert
        destination_attributes:
          $ref: '#/components/schemas/SyncDestinationAttributes'
        source_attributes:
          $ref: '#/components/schemas/SyncSourceAttributes'
        mappings:
          type: array
          description: Array of mapping objects defining how source fields map to destination fields.
          items:
            $ref: '#/components/schemas/SyncMapping'
        alert_attributes:
          type: array
          description: Array of alert configuration objects determining when and how to send alerts.
          items:
            $ref: '#/components/schemas/SyncAlertAttributes'
        advanced_configuration:
          $ref: '#/components/schemas/SyncAdvancedConfiguration'
        mode:
          $ref: '#/components/schemas/SyncMode'
        paused:
          type: boolean
          description: Whether or not this sync should be paused.
        field_behavior:
          type: string
          description: How destination fields are updated.
        field_normalization:
          type: string
          description: If field_behavior is 'sync_all_properties', how automatic mappings should be named.
        field_order:
          type: string
          description: How the destination fields should be ordered.
        sync_behavior_family:
          type: string
          description: Behavior family for the sync.
        high_water_mark_attribute:
          type: string
          description: Name of the timestamp column for high‑water‑mark diffing strategy.
        high_water_mark_attributes:
          $ref: '#/components/schemas/SyncHighWaterMarkAttributes'
        validate_only:
          type: boolean
          description: When true, checks if the given payload is valid to configure a sync. Does not create the sync.
        failed_run_notifications_enabled:
          type: boolean
          description: Deprecated flag: when true, will email on sync failures and recoveries.
        failed_record_notifications_enabled:
          type: boolean
          description: Deprecated flag: when true, will email on invalid/rejected record thresholds.
        failed_record_notifications_threshold_percent:
          type: integer
          description: Deprecated: threshold percent of invalid/rejected records to trigger notification.
        historical_sync_operation:
          type: string
          description: How the first sync should handle historical records for append operations.
        mirror_strategy:
          type: string
          description: Strategy for mirror syncs.
      required:
        - operation
        - destination_attributes
        - source_attributes
        - mappings

    SyncData:
      type: object
      properties:
        id:
          type: integer
          description: ID of the sync.
        status:
          type: string
          description: Status of the sync (e.g., ready).
        created_at:
          type: string
          format: date-time
          description: Timestamp when the sync was created.
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the sync was last updated.
        label:
          type: string
          description: A label to give to this sync.
        operation:
          type: string
          description: How records are synced to the destination.
        destination_attributes:
          $ref: '#/components/schemas/SyncDestinationAttributes'
        source_attributes:
          $ref: '#/components/schemas/SyncSourceAttributes'
        mappings:
          type: array
          items:
            $ref: '#/components/schemas/SyncMapping'
        alert_attributes:
          type: array
          items:
            $ref: '#/components/schemas/SyncAlertAttributes'
        advanced_configuration:
          $ref: '#/components/schemas/SyncAdvancedConfiguration'
        mode:
          $ref: '#/components/schemas/SyncMode'
        paused:
          type: boolean
          description: Whether or not this sync should be paused.
        field_behavior:
          type: string
          description: How destination fields are updated.
        field_normalization:
          type: string
          description: If field_behavior is 'sync_all_properties', how automatic mappings should be named.
        field_order:
          type: string
          description: How the destination fields should be ordered.
        sync_behavior_family:
          type: string
          description: Behavior family for the sync.
        high_water_mark_attribute:
          type: string
          description: Name of the timestamp column for high‑water‑mark diffing strategy.
        high_water_mark_attributes:
          $ref: '#/components/schemas/SyncHighWaterMarkAttributes'
        validate_only:
          type: boolean
          description: When true, checks if the given payload is valid to configure a sync. Does not create the sync.
        failed_run_notifications_enabled:
          type: boolean
          description: Deprecated flag: when true, will email on sync failures and recoveries.
        failed_record_notifications_enabled:
          type: boolean
          description: Deprecated flag: when true, will email on invalid/rejected record thresholds.
        failed_record_notifications_threshold_percent:
          type: integer
          description: Deprecated: threshold percent of invalid/rejected records to trigger notification.
        historical_sync_operation:
          type: string
          description: How the first sync should handle historical records for append operations.
        mirror_strategy:
          type: string
          description: Strategy for mirror syncs.
        match_rate_details:
          $ref: '#/components/schemas/SyncMatchRateDetails'

    SyncDestinationAttributes:
      type: object
      properties:
        connection_id:
          type: integer
          description: ID of the destination connection.
        object:
          type: string
          description: Destination object (table, entity) to sync into.
      required:
        - connection_id
        - object

    SyncSourceAttributes:
      type: object
      properties:
        connection_id:
          type: integer
          description: ID of the source connection.
        object:
          $ref: '#/components/schemas/SyncSourceObject'
      required:
        - connection_id
        - object

    SyncSourceObject:
      type: object
      properties:
        type:
          type: string
          description: Source object type (dataset, table, etc.)
        id:
          type: integer
          description: ID of the dataset source.
        table_catalog:
          type: string
          description: Catalog name for the table in the warehouse.
        table_schema:
          type: string
          description: Schema name for the table in the warehouse.
        table_name:
          type: string
          description: Table name in the warehouse schema.

    SyncMapping:
      type: object
      properties:
        from:
          $ref: '#/components/schemas/SyncMappingFrom'
        to:
          type: string
          description: Destination field or property name.
        is_primary_identifier:
          type: boolean
          description: Whether this mapping is used as the primary identifier.
        lookup_object:
          type: string
          description: Destination lookup object name if using a lookup.
        lookup_field:
          type: string
          description: Field to look up on the destination object if using a lookup.
      required:
        - from
        - to

    SyncMappingFrom:
      type: object
      properties:
        type:
          type: string
          description: Type of source data reference (column, constant_value, etc.)
        data:
          description: Data or value used from the source side (column name or constant value object).
      required:
        - type
        - data

    SyncAlertAttributes:
      type: object
      properties:
        type:
          type: string
          description: Type of alert configuration.
        send_for:
          type: string
          description: When to send the alert (first_time, every_time, etc.)
        should_send_recovery:
          type: boolean
          description: Whether to send a recovery notification when issue is resolved.
        options:
          description: Additional options specific to the alert type.

    SyncAdvancedConfiguration:
      type: object
      properties:
        data_source_country:
          type: string
          description: Country or countries of the data source (e.g., 'US, GB').
        bulk_id_lookup:
          type: boolean
          description: Whether to use bulk ID lookup optimization.

    SyncMode:
      type: object
      properties:
        type:
          type: string
          description: SyncMode type (e.g., triggered).
        triggers:
          $ref: '#/components/schemas/SyncTriggers'

    SyncTriggers:
      type: object
      properties:
        schedule:
          $ref: '#/components/schemas/SyncSchedule'

    SyncSchedule:
      type: object
      properties:
        frequency:
          type: string
          description: Run frequency (e.g., daily)
        hour:
          type: integer
          description: Hour of day when the sync runs (24‑hour clock)
        minute:
          type: integer
          description: Minute of hour when the sync runs

    SyncHighWaterMarkAttributes:
      type: object
      properties:
        use_high_water_mark_diff_type:
          type: boolean
          description: Whether to use the high water mark diff type.
        column_name:
          type: string
          description: Name of the timestamp column used for high water mark diffing.
    SyncMatchRateDetails:
      type: object
      properties:
        match_rate:
          type: number
          description: Overall match rate for the sync.
        match_rate_last_calculated_at:
          type: string
          format: date-time
          description: Timestamp when match rate was last calculated.


    CreateSyncResponse:
      type: object
      properties:
        status:
          type: string
          description: Outcome of the operation.
        data:
          $ref: '#/components/schemas/SyncIdData'
      required:
        - status
        - data

    SyncIdData:
      type: object
      properties:
        sync_id:
          type: integer
          description: ID of the newly created sync.
      required:
        - sync_id

    UpdateSyncResponse:
      type: object
      properties:
        status:
          type: string
          description: Outcome of the operation.
        data:
          $ref: '#/components/schemas/Sync'
      required:
        - status
        - data

    FetchSyncResponse:
      type: object
      properties:
        status:
          type: string
          description: Outcome of the fetch request.
        data:
          $ref: '#/components/schemas/Sync'
      required:
        - status
        - data
